/*
 *  	Created on: 18/09/2023
 *      LAYER : MCAL
 *      Author: Mohamed sarary
 *      File  : ADC_Config.h
 */

#ifndef MCAL_ADC_ADC_CONFIG_H_
#define MCAL_ADC_ADC_CONFIG_H_


/*
 * ADC VREF OPTIONS :
 * 1- AREF
 * 2- AVCC
 * 3- INT_2_56
 */
#define ADC_VREF_MODE				AVCC

/*
 * ADC PRESCALLER OPTIONS :
 * 1- ADC_DIV_2
 * 2- ADC_DIV_4
 * 3- ADC_DIV_8
 * 4- ADC_DIV_16
 * 5- ADC_DIV_32
 * 6- ADC_DIV_64
 * 7- ADC_DIV_128
 */
#define ADC_PRESACLLER_MODE  		ADC_DIV_8

/*
 * ADC ADJUSTMENT OPTIONS :
 * 1- ADC_LEFT_ADJ
 * 2- ADC_RIGHT_ADJ
 */
#define ADC_ADJ_MODE    			ADC_RIGHT_ADJ

/*
 * ADC RUNNING OPTIONS :
 * 1- ADC_SINGLE_CONV
 * 2- ADC_AUTO_TRIG
 */

#define ADC_RUNNING_MODE			ADC_SINGLE_CONV


/*
 * 			******* P.S : THIS MODE IS RUNNING ONLY IF ADC_RUNNING_MODE == ADC_AUTO_TRIG *******
 * ADC AUTO TRIGGER OPTIONS :
 * 1- ADC_FREE_RUNNING
 * 2- ADC_ANALOG_COMP
 * 3- ADC_EXTI_REQ0
 * 4- ADC_TIMER0_CMP
 * 5- ADC_TIMER0_OVF
 * 6- ADC_TIMER1_CMP
 * 7- ADC_TIMER1_OVF
 * 8- ADC_TIMER1_CP_EV
 */
#define ADC_AUTO_TRIGGER_MODE		ADC_FREE_RUNNING


#endif /* MCAL_ADC_ADC_CONFIG_H_ */
