/*
 *  	Created on: 27/09/2023
 *      LAYER : MCAL
 *      Author: Mohamed sarary
 *      File  : USART_Config.h
 */

#ifndef MCAL_USART_USART_CONFIG_H_
#define MCAL_USART_USART_CONFIG_H_

/* SYSTEM FREQUENCY CONFIG TO CALCULATE BAUD RATE */
#define SYSTEM_FREQ				8000000UL

/* BAUD RATE USED IN USART */
#define USART_BAUD_RATE			9600UL

/* TIME OUT FOR FUNCTIONS */
#define USART_u32TIMEOUT	         	10000UL

/*
 * USART SYSTEM SPEED OPTIONS :
 * 1- USART_X1
 * 2- USART_X2
 */
#define USART_SYSTEM_SPEED      	 USART_X1

/*
 * USART STOP BITS OPTIONS :
 * 1- STOP_1BIT
 * 2- STOP_2BIT
 */
#define USART_STOP_BITS				STOP_1BIT

/*
 * USART PARITY STATE OPTIONS :
 * 1- DISABLE
 * 2- EVEN_PARITY
 * 3- ODD_PARITY
 */
#define USART_PARITY_STATE			DISABLE

/*
 * USART MODE OPTIONS :
 * 1- USART_ASYNC
 * 2- USART_SYNC
 */

#define USART_MODE					USART_ASYNC

/*
 * USART DATA SIZE OPTIONS :
 * 1- DATA_5BITS
 * 2- DATA_6BITS
 * 3- DATA_7BITS
 * 4- DATA_8BITS
 * 5- DATA_9BITS
 */
#define USART_DATA_SIZE			 	DATA_8BITS

/*
 * OPTIONS :
 * 1- DISABLE
 * 2- ENABLE
 */
#define USART_MBCM					 	DISABLE
#define USART_RX_COMPLETE_INT		 	DISABLE
#define USART_TX_COMPLETE_INT			DISABLE
#define USART_UDR_EMPTY_ENABLE			ENABLE
#define USART_RECEIVER_ENABLE			ENABLE
#define USART_TRANSMITTER_ENABLE		ENABLE

/*
 *  USART CLOCK POLARITY OPTIONS :
 * 1- XCK_RISING_TX_XCH_FALLING_RX
 * 2- XCK_RISING_RX_XCH_FALLING_TX
 */
#define USART_CLOCK_POLARITY		XCK_RISING_TX_XCH_FALLING_RX

#endif /* MCAL_USART_USART_CONFIG_H_ */
