/*
 *  	Created on: 18/05/2023
 *      Driver: ADC Driver
 *      Author: Mohamed sarary
 *      File  : ADC_Program.c
 */


#include "ADC_Config.h"
#include "ADC_Interface.h"
#include "ADC_Private.h"
#include "../../MCAL/DIO/DIO_Confing.h"
#include "../../MCAL/DIO/DIO_Private.h"
#include "../../MCAL/DIO/DIO_interface.h"
#include "../../SERVICES/BIT_MATH.h"
#include "../../SERVICES/STD_TYPES.h"
#include "../../SERVICES/errorStates.h"


u8 ADC_u8Init(void)
{
	u8 Func_State = Func_NOK ;
	/*    SET VOLTAGE OF THE ADC    */
#if ADC_VREF_MODE == ADC_AREF_INTERNAL_OFF
	CLR_BIT(ADMUX,REFS0);
	CLR_BIT(ADMUX,REFS1);

#elif ADC_VREF_MODE == ADC_5V_INTERNAL
	SET_BIT(ADMUX,REFS0);
	CLR_BIT(ADMUX,REFS1);

#elif ADC_VREF_MODE == ADC_INTERNAL_VREF
	SET_BIT(ADMUX,REFS0);
	SET_BIT(ADMUX,REFS1);
#endif

	/*    SET ADJUST MODE OF THE ADC    */
#if ADC_ADJUSTMENT_MODE == ADC_LEFT_ADJUSTMENT
	SET_BIT(ADMUX,ADLAR);

#elif ADC_ADJUSTMENT_MODE == ADC_RIGHT_ADJUSTMENT
	CLR_BIT(ADMUX,ADLAR);
#endif

	/*    SET CHANNEL OF THE ADC    */
#if ADC_CHANNEL_MODE == ADC_ADC0_PORTA_PIN0
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC1_PORTA_PIN1
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC2_PORTA_PIN2
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC3_PORTA_PIN3
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC4_PORTA_PIN4
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC5_PORTA_PIN5
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC6_PORTA_PIN6
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC7_PORTA_PIN7
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC0_ADC0_DIFFERNTIAL_10x
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC1_ADC0_DIFFERNTIAL_10x
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC0_ADC0_DIFFERNTIAL_200x
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC1_ADC0_DIFFERNTIAL_200x
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC2_ADC2_DIFFERNTIAL_10x
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC3_ADC2_DIFFERNTIAL_10x
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);


#elif ADC_CHANNEL_MODE == ADC_ADC2_ADC2_DIFFERNTIAL_200x
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC3_ADC2_DIFFERNTIAL_200x
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	CLR_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC0_ADC1_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC1_ADC1_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC2_ADC1_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC3_ADC1_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC4_ADC1_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC5_ADC1_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC6_ADC1_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC7_ADC1_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	CLR_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC0_ADC2_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC1_ADC2_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC2_ADC2_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC3_ADC2_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	SET_BIT(ADMUX , MUX1);
	CLR_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC4_ADC2_DIFFERNTIAL_1x
	CLR_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#elif ADC_CHANNEL_MODE == ADC_ADC5_ADC2_DIFFERNTIAL_1x
	SET_BIT(ADMUX , MUX0);
	CLR_BIT(ADMUX , MUX1);
	SET_BIT(ADMUX , MUX2);
	SET_BIT(ADMUX , MUX3);
	SET_BIT(ADMUX , MUX4);

#endif

	/*    SET PRESCALLER OF THE ADC    */
#if ADC_PRESCALLER_MODE	==	ADC_DIV_BY2
	SET_BIT(ADCSRA , ADPS0);
	CLR_BIT(ADCSRA , ADPS1);
	CLR_BIT(ADCSRA , ADPS2);

#elif ADC_PRESCALLER_MODE	==	ADC_DIV_BY4
	CLR_BIT(ADCSRA , ADPS0);
	SET_BIT(ADCSRA , ADPS1);
	CLR_BIT(ADCSRA , ADPS2);

#elif ADC_PRESCALLER_MODE	==	ADC_DIV_BY8
	SET_BIT(ADCSRA , ADPS0);
	SET_BIT(ADCSRA , ADPS1);
	CLR_BIT(ADCSRA , ADPS2);

#elif ADC_PRESCALLER_MODE	==	ADC_DIV_BY16
	CLR_BIT(ADCSRA , ADPS0);
	CLR_BIT(ADCSRA , ADPS1);
	SET_BIT(ADCSRA , ADPS2);

#elif ADC_PRESCALLER_MODE	==	ADC_DIV_BY32
	SET_BIT(ADCSRA , ADPS0);
	CLR_BIT(ADCSRA , ADPS1);
	SET_BIT(ADCSRA , ADPS2);

#elif ADC_PRESCALLER_MODE	==	ADC_DIV_BY64
	CLR_BIT(ADCSRA , ADPS0);
	SET_BIT(ADCSRA , ADPS1);
	SET_BIT(ADCSRA , ADPS2);

#elif ADC_PRESCALLER_MODE	==	ADC_DIV_BY128
	SET_BIT(ADCSRA , ADPS0);
	SET_BIT(ADCSRA , ADPS1);
	SET_BIT(ADCSRA , ADPS2);

#endif

	/*    SET INTERRUPT OF THE ADC    */
#if ADC_INTERRUPT_MODE == ADC_INTERRUPT_MODEOFF
	CLR_BIT(ADCSRA , ADIE);
#elif ADC_INTERRUPT_MODE == ADC_INTERRUPT_MODEOM
	SET_BIT(ADCSRA , ADIE);
#endif
/*	CLEAR ADC INTERRUPT FLAG	*/
	SET_BIT(ADCSRA , ADIF);


	/*    SET MODE OF THE ADC    */
#if ADC_WORKING_MODE == ADC_SINGLE_MODE
	CLR_BIT(ADCSRA , ADATE);
#elif ADC_WORKING_MODE == ADC_AUTO_TRIGGER_MODE
	SET_BIT(ADCSRA , ADATE);
#endif

	/*	 AUTO TRIG MODE		*/
#if ADC_AUTO_TRIG_MODE == ADC_FREE_RUNNING_MODE
	CLR_BIT(SFIOR , ADTS0);
	CLR_BIT(SFIOR , ADTS1);
	CLR_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_ANALOG_COMPRATOR_MODE
	SET_BIT(SFIOR , ADTS0);
	CLR_BIT(SFIOR , ADTS1);
	CLR_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_EXT_INTERRUPT0_MODE
	CLR_BIT(SFIOR , ADTS0);
	SET_BIT(SFIOR , ADTS1);
	CLR_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_TIMER0_COMPARE_MODE
	SET_BIT(SFIOR , ADTS0);
	SET_BIT(SFIOR , ADTS1);
	CLR_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_TIMER0_OVERFLOW_MODE
	CLR_BIT(SFIOR , ADTS0);
	CLR_BIT(SFIOR , ADTS1);
	SET_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_TIMER_COMPARE_B_MODE
	SET_BIT(SFIOR , ADTS0);
	CLR_BIT(SFIOR , ADTS1);
	SET_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_TIMER1_OVERFLOW_MODE
	CLR_BIT(SFIOR , ADTS0);
	SET_BIT(SFIOR , ADTS1);
	SET_BIT(SFIOR , ADTS2);

#elif ADC_AUTO_TRIG_MODE == ADC_TIMER1_CAPTURE_MODE
	SET_BIT(SFIOR , ADTS0);
	SET_BIT(SFIOR , ADTS1);
	SET_BIT(SFIOR , ADTS2);
#endif


	/* FINALLY ENABLE ADC */
	SET_BIT(ADCSRA , ADEN);
	Func_State = Func_OK ;
	return Func_State ;
}

u8 ADC_u8Enable(void)
{
	u8 Func_State = Func_NOK ;
	SET_BIT(ADCSRA , ADEN);
	Func_State = Func_OK ;
	return Func_State ;
}

u8 ADC_u8Disable(void)
{
	u8 Func_State = Func_NOK ;
	CLR_BIT(ADCSRA , ADEN);
	Func_State = Func_OK ;
	return Func_State ;

}

u16 ADC_u16GetResult(u16* Copy_u16_ADC_Res)
{
	u8 Func_State = Func_NOK;
	*Copy_u16_ADC_Res = 0 ;
	/* ADC START CONVERSION */
	SET_BIT(ADCSRA,ADSC);

	/* Wait Until The Conversion is Done  : Block Inside The Loop Until The Flag is Set */
	while(GET_BIT(ADCSRA,ADIF)==0);

#if ADC_ADJUSTMENT_MODE == ADC_RIGHT_ADJUSTMENT
	*Copy_u16_ADC_Res = ADCL | (ADCH<<8);
#elif ADC_ADJUSTMENT_MODE == ADC_LEFT_ADJUSTMENT
	*Copy_u16_ADC_Res = ADCH | (ADCL<<8);
#endif
	SET_BIT(ADCSRA , ADIF);
	Func_State = Func_OK ;
	return Func_State ;
}

u16 ADC_u16GETChannelResult(u8 Copy_u8ADC_Channel , u8* Copy_u8ADC_ChannelRes  )
{
	u8 Func_State = Func_NOK;
	*Copy_u8ADC_ChannelRes = 0 ;

	/* channel number must be from A0 --> A7 */
	Copy_u8ADC_Channel &= 0x07;

	/* clear first 5 bits in the ADMUX (channel number MUX4:0 bits) before set the required channel */
		CLR_BIT(ADMUX,MUX0);
		CLR_BIT(ADMUX,MUX1);
		CLR_BIT(ADMUX,MUX2);
		CLR_BIT(ADMUX,MUX3);
		CLR_BIT(ADMUX,MUX4);

	/* choose the correct channel by setting the channel number in MUX4:0 bits */
			ADMUX |= Copy_u8ADC_Channel;

#if ADC_ADJUSTMENT_MODE == ADC_RIGHT_ADJUSTMENT
	*Copy_u8ADC_ChannelRes = ADCL | (ADCH<<8);
#elif ADC_ADJUSTMENT_MODE == ADC_LEFT_ADJUSTMENT
	*Copy_u8ADC_ChannelRes = ADCH | (ADCL<<8);
#endif
	SET_BIT(ADCSRA , ADIF);
	Func_State = Func_OK ;
	return Func_State ;

}


